spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate

  # Dev environment-specific database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/groble_dev_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  # Dev environment-specific OAuth2 settings
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://dev.groble.im/login/oauth2/callback/kakao
          naver:
            redirect-uri: https://dev.groble.im/login/oauth2/callback/naver
          google:
            redirect-uri: https://dev.groble.im/login/oauth2/callback/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: linkit@linkit.im
    password: fatu mxkw wcuy pkdf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
