spring:
  profiles:
    active: local
  application:
    name: groble
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/groble_dev_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kk040802
  jpa:
    hibernate:
     ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 69e5fb5a044dcc3eb859a1a3d1689842
            client-secret: ZsynGsfqoAfUeHzaoyrP0r10MMpXqCwm
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: IhcluuW4bKYE4gfP42ht
            client-secret: Flcyd2M9Qb
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          google:
            client-id: 278417909651-glogb0baquf7gces2pjvd77kiedennea.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

# JWT Configuration
app:
  jwt:
    access-token:
      secret: 6M1boNRsyYPgKuR197f4w2uuh8DXfYyjxgPJKmINtHo=
      expiration-ms: 3600000  # 1 hour
    refresh-token:
      secret: bZvf0E0wsJXugzxv2m25c5zHvJrNfvsQIjzU6eBScbk=
      expiration-ms: 604800000  # 7 days
    issuer: groble-auth-service

  frontend-url: http://localhost:3000
  backend-url: http://localhost:8080
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# Logging
logging:
  level:
    root: INFO
    liaison: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
