spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  # Local environment-specific OAuth2 settings
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: linkit@linkit.im
    password: fatu mxkw wcuy pkdf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
