version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: root
  ApplicationStarted:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root