ALTER TABLE orders
    MODIFY COLUMN status
    ENUM('CANCELLED', 'EXPIRED', 'FAILED', 'PAID', 'PENDING', 'CANCEL_REQUEST')
    NOT NULL;

ALTER TABLE purchases
    ADD COLUMN status
    ENUM('PENDING', 'COMPLETED', 'CANCEL_REQUESTED', 'REFUND_REQUESTED', 'REFUNDED', 'FAILED')
    NOT NULL;
