openapi: 3.0.3
info:
  title: Notification API
  description: 알림 관련 API 명세서
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://api.groble.com
    description: Production server

paths:
  /api/v1/notifications:
    get:
      tags:
        - Notification
      summary: 알림 전체 조회
      description: 사용자의 모든 알림을 조회합니다.
      operationId: getNotifications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 알림 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationItemsResponse'
        '401':
          $ref: './common-schemas.yaml#/components/responses/Unauthorized'
        '500':
          $ref: './common-schemas.yaml#/components/responses/InternalServerError'
    
    delete:
      tags:
        - Notification
      summary: 알림 전체 삭제
      description: 사용자의 모든 알림을 삭제합니다.
      operationId: deleteAllNotifications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 모든 알림이 삭제되었습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResponse'
        '401':
          $ref: './common-schemas.yaml#/components/responses/Unauthorized'
        '500':
          $ref: './common-schemas.yaml#/components/responses/InternalServerError'

  /api/v1/notifications/{notificationId}:
    delete:
      tags:
        - Notification
      summary: 알림 단일 삭제
      description: 특정 알림을 삭제합니다.
      operationId: deleteNotification
      security:
        - bearerAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          description: 삭제할 알림 ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 알림이 삭제되었습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResponse'
        '401':
          $ref: './common-schemas.yaml#/components/responses/Unauthorized'
        '404':
          $ref: './common-schemas.yaml#/components/responses/NotFound'
        '500':
          $ref: './common-schemas.yaml#/components/responses/InternalServerError'

components:
  schemas:
    # GrobleResponse 구조를 반영한 공통 응답 형식
    GrobleResponse:
      type: object
      required:
        - status
        - code
        - message
        - timestamp
      properties:
        status:
          type: string
          enum: [SUCCESS, ERROR, FAIL]
          description: 응답 상태
          example: SUCCESS
        code:
          type: integer
          description: HTTP 상태 코드 또는 커스텀 코드
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: "요청이 성공적으로 처리되었습니다."
        data:
          type: object
          description: 응답 데이터 (요청 성공 시)
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'
          nullable: true
        timestamp:
          type: string
          format: date-time
          description: 응답 생성 시간
          example: "2025-05-06 04:26:26"
    
    ErrorDetail:
      type: object
      properties:
        exception:
          type: string
          description: 예외 클래스명
        message:
          type: string
          description: 에러 메시지
        field:
          type: string
          description: 에러가 발생한 필드
        value:
          type: string
          description: 문제가 된 값
    
    # Void 타입 응답 (데이터 없음)
    VoidResponse:
      allOf:
        - $ref: '#/components/schemas/GrobleResponse'
        - type: object
          properties:
            data:
              type: object
              nullable: true
              example: null
    
    # NotificationItems를 포함한 응답
    NotificationItemsResponse:
      allOf:
        - $ref: '#/components/schemas/GrobleResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/NotificationItems'
    
    NotificationItems:
      type: object
      required:
        - notifications
        - unreadCount
      properties:
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/NotificationItem'
        unreadCount:
          type: integer
          description: 읽지 않은 알림 개수
          example: 5
    
    NotificationItem:
      type: object
      required:
        - notificationId
        - type
        - title
        - content
        - isRead
        - createdAt
      properties:
        notificationId:
          type: integer
          format: int64
          description: 알림 ID
          example: 1
        type:
          type: string
          description: 알림 타입
          enum:
            - ORDER_STATUS_CHANGED
            - NEW_MESSAGE
            - SYSTEM_ANNOUNCEMENT
          example: ORDER_STATUS_CHANGED
        title:
          type: string
          description: 알림 제목
          example: "주문 상태가 변경되었습니다"
        content:
          type: string
          description: 알림 내용
          example: "주문번호 12345의 상태가 '배송중'으로 변경되었습니다."
        isRead:
          type: boolean
          description: 읽음 여부
          example: false
        createdAt:
          type: string
          format: date-time
          description: 알림 생성 시간
          example: "2024-01-15T10:30:00Z"
        relatedId:
          type: integer
          format: int64
          description: "관련 엔티티 ID (예: 주문 ID, 메시지 ID 등)"
          example: 12345
        
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
