package liaison.groble.application.notification.enums;

public enum KakaoNotificationType {
  WELCOME,
  PURCHASE_COMPLETE,
  GUEST_PURCHASE_COMPLETE,
  SUBSCRIPTION_FIRST_PAYMENT,
  SUBSCRIPTION_RENEWAL_PAYMENT,
  SUBSCRIPTION_PAYMENT_FAILED, // 정기결제 1차 실패 (구매자)
  SUBSCRIPTION_CANCELLED, // 정기결제 3회 실패로 해지 (구매자)
  SUBSCRIPTION_GRACE_PERIOD_EXPIRED, // 유예기간 만료 (구매자)
  SELLER_SUBSCRIPTION_FIRST_PAYMENT,
  SELLER_SUBSCRIPTION_RENEWAL_PAYMENT,
  SELLER_SUBSCRIPTION_GRACE_PERIOD_EXPIRED, // 유예기간 만료 (판매자)
  SALE_COMPLETE,
  CONTENT_DISCONTINUED,
  REVIEW_REGISTERED,
  VERIFICATION_COMPLETE,
  VERIFICATION_REJECTED,
  SETTLEMENT_COMPLETED,
  APPROVE_CANCEL,
  HOME_TEST_PURCHASE
}
