package liaison.groble.application.notification.enums;

public enum KakaoNotificationType {
  WELCOME,
  PURCHASE_COMPLETE,
  GUEST_PURCHASE_COMPLETE,
  SALE_COMPLETE,
  CONTENT_DISCONTINUED,
  REVIEW_REGISTERED,
  VERIFICATION_COMPLETE,
  VERIFICATION_REJECTED,
  SETTLEMENT_COMPLETED,
  APPROVE_CANCEL,
  HOME_TEST_PURCHASE
}
