spring:
  datasource:
    url: jdbc:mysql://prod-mysql:3306/groble_prod_database
    username: groble_root
    password: fldpwhdrmfhqmfproddb!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: groble-prod-redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 69e5fb5a044dcc3eb859a1a3d1689842
            client-secret: ZsynGsfqoAfUeHzaoyrP0r10MMpXqCwm
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://api.groble.im/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: IhcluuW4bKYE4gfP42ht
            client-secret: Flcyd2M9Qb
            redirect-uri: https://api.groble.im/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          google:
            client-id: 278417909651-glogb0baquf7gces2pjvd77kiedennea.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://api.groble.im/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            user-name-attribute: sub
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    host: smtp.gmail.com
    port: 587
    username: groble@groble.im
    password: oluv nucy taqt wcfq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

cloud:
  aws:
    credentials:
      access-key: AKIAX25EZZBU36BV5JNJ
      secret-key: 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
      instance-profile: false
    s3:
      bucket: image.groble.im
      cloud-front-image-domain: https://image.groble.im
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

app:
  security:
    password-reset-secret: r5IsQJQ8xeCdF6cr/yk/pk0FIerxYJPWyscXkw7hT+c=


ncp:
  sms:
    access-key: ncp_iam_BPAMKR13brr0H7igHp6Q
    secret-key: ncp_iam_BPKMKR28ZyFTnKERSY79Jr0T2zgrcCUm0u
    service-id: ncp:sms:kr:353543594810:groble
    send-from: "01046415411"

discord:
  webhook:
    alert:
      member:
        url: https://discord.com/api/webhooks/1379000100826910822/H_NhG2fhvL548hGvpUXMxXODrLi2GCzxFlzKNBuSt9_0ny_c9FAK1cKcgslL_Xqyh6nW
      personal-maker:
        url: https://discord.com/api/webhooks/1379500169271316680/Try-M1QrNa8SGmlJ2yf_LnXdIR0j0tp94iS8qwGbdNuOtcH5O_YrWr8I8OC0aEkIvzg0
      business-maker:
        url: https://discord.com/api/webhooks/1379500310002798742/nowMpFWuSR95Or_ByjQwRZbj1K0VveepkDKNN9ogeZPpFvrpdH94DnwNGsTsPZ_bjbzt
